# Generated by Django 5.2.8 on 2026-04-15 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRunLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('tweets_posted', models.PositiveIntegerField(default=0)),
                ('replies_posted', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('balanced', 'Balanced'), ('aggressive', 'Aggressive'), ('max_growth', 'Max Growth')], default='balanced', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('target_tweets_per_day', models.PositiveIntegerField(default=5)),
                ('target_replies_per_day', models.PositiveIntegerField(default=20)),
                ('min_post_interval_minutes', models.PositiveIntegerField(default=90)),
                ('min_reply_interval_seconds', models.PositiveIntegerField(default=180)),
                ('auto_post_enabled', models.BooleanField(default=True)),
                ('review_high_risk_only', models.BooleanField(default=True)),
                ('relevance_threshold', models.FloatField(default=75.0)),
                ('kill_switch', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostMetricSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('replies', models.PositiveIntegerField(default=0)),
                ('reposts', models.PositiveIntegerField(default=0)),
                ('profile_visits', models.PositiveIntegerField(default=0)),
                ('follows', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('posted', 'Posted'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('text', models.TextField()),
                ('twitter_id', models.CharField(blank=True, max_length=64)),
                ('risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tweet_id', models.CharField(max_length=64)),
                ('source_author_handle', models.CharField(max_length=64)),
                ('source_text', models.TextField()),
                ('relevance_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('replied', 'Replied'), ('dismissed', 'Dismissed')], default='new', max_length=16)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='run_reason',
            field=models.CharField(default='daily_autopilot', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.prompt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('posted', 'Posted'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='post',
            name='system_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.systemprompt'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='model_name',
            field=models.CharField(default='openai:gpt-4.1-mini', max_length=128),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'status', 'scheduled_for'], name='api_post_user_id_be00dc_idx'),
        ),
        migrations.AddField(
            model_name='agentrunlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growthpolicy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmetricsnapshot',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='api.post'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replytarget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='api.replytarget'),
        ),
        migrations.AddIndex(
            model_name='agentrunlog',
            index=models.Index(fields=['user', 'created_at'], name='api_agentru_user_id_250255_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyusage',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_daily_usage_user_date'),
        ),
        migrations.AddIndex(
            model_name='postmetricsnapshot',
            index=models.Index(fields=['captured_at'], name='api_postmet_capture_5fd353_idx'),
        ),
        migrations.AddIndex(
            model_name='replytarget',
            index=models.Index(fields=['user', 'status', 'relevance_score'], name='api_replyta_user_id_979379_idx'),
        ),
        migrations.AddConstraint(
            model_name='replytarget',
            constraint=models.UniqueConstraint(fields=('user', 'source_tweet_id'), name='uniq_reply_target_user_tweet'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['status', 'scheduled_for'], name='api_reply_status_19a71d_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['user', 'status', 'scheduled_for'], name='api_reply_user_id_60b12a_idx'),
        ),
    ]
