[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asgiref==3.10.0",
    "certifi==2025.10.5",
    "cffi==2.0.0",
    "charset-normalizer==3.4.4",
    "cryptography==46.0.7",
    "defusedxml==0.7.1",
    "django==5.2.13",
    "django-filter==25.2",
    "djangorestframework==3.16.1",
    "djangorestframework-simplejwt==5.5.1",
    "djoser==2.3.3",
    "idna==3.11",
    "oauthlib==3.3.1",
    "pycparser==2.23",
    "pydantic>=2.13.0",
    "pydantic-ai>=1.82.0",
    "pyjwt==2.10.1",
    "python3-openid==3.2.0",
    "requests==2.33.0",
    "requests-oauthlib==2.0.0",
    "social-auth-app-django==5.6.0",
    "social-auth-core==4.8.1",
    "sqlparse==0.5.3",
    "urllib3==2.6.3",
]
